"""项目规范文档模板（只产字符串，不写磁盘）。"""

from __future__ import annotations

from textwrap import dedent


DEFAULT_PLATFORMS = ("codex", "claude", "cursor", "kiro", "qoder", "antigravity")

PLATFORM_DISPLAY = {
    "codex": "Codex",
    "claude": "Claude Code",
    "cursor": "Cursor",
    "kiro": "Kiro",
    "qoder": "Qoder",
    "antigravity": "Antigravity",
}

PLATFORM_ENTRYPOINTS = {
    "codex": "AGENTS.md",
    "claude": "CLAUDE.md",
    "cursor": ".cursor/rules/agentflow.mdc",
    "kiro": ".kiro/steering/agentflow.md",
    "qoder": ".qoder/skills/agentflow/SKILL.md",
    "antigravity": ".agent/skills/agentflow/SKILL.md",
}

AGENTFLOW_GENERATED_MARKER = "<!-- Generated by AgentFlow. Safe to delete. -->"


def agents_md() -> str:
    return dedent(
        """\
        # AGENTS.md

        本文件是本项目的**唯一总入口**。开工前必读，每次必读。

        ## Flow 与本项目的关系

        Flow 是轻巧的离线 CLI，只负责铺设规范地基：生成 `.agentflow/` 骨架、
        按需写入所选 AI 工具的薄入口、`check` 校验文件是否齐全。

        Flow **不**绑定特定 agent 或编辑器，**不**编排工作流，**不**强制模型行为。
        文档填写与维护靠本文件中的契约与提示词；是否遵守取决于 AI 与开发者，而非工具拦截。

        ## 项目文档（位于 `.agentflow/`）

        规范分散在以下文件中，**每个文件边界严格不重叠**。
        需要时按索引阅读，不要把所有信息都塞进本文件：

        - [`project.md`](project.md) — 项目是什么：定位、技术栈、架构、运行方式
        - [`conventions.md`](conventions.md) — 怎么写代码：命名、结构、风格、禁用模式
        - [`business.md`](business.md) — 业务是什么：领域概念、核心流程、术语表
        - [`pitfalls.md`](pitfalls.md) — 踩过的坑：历史教训、不再重蹈的决策
        - [`skills/README.md`](skills/README.md) — 专项 skill 路由表

        ## 工作纪律

        1. **开工前**：通读 `.agentflow/` 下所有 `.md`。重述目标、范围、非目标后再动手。
        2. **范围最小**：只改与当前请求相关的文件。不碰无关模块。
        3. **验证优先**：改完先跑可用的检查（类型/测试/lint），再报告完成。
        4. **交接标准**：完成时报告——改了哪些文件、跑了什么命令、结果、遗留风险、下一步。

        ## 文档维护契约

        以下约定面向 AI 编码助手，靠提示词生效，Flow 本身不强制执行。

        - **首次接手**：若 `project.md` 等仍有未填章节，**第一项任务**是分析代码库并填写，
          然后再做用户要求的事。按每个文件顶部的边界声明填写。
        - **改动后更新**：完成有意义的改动后，更新对应文档。
          改了架构 → `project.md`；定了新规范 → `conventions.md`；
          理解了新业务 → `business.md`；踩了坑 → `pitfalls.md`。
        - **不重复**：每条信息只出现在一个文档里。写到一半发现「别处也有」，
          说明放错位置——按边界声明判断归属，只保留一处。
        - **宁缺毋滥**：某个文档可以很短，但不要为「完整」而堆砌。空章节比错位章节好。
        - **以代码为准**：文档与代码冲突时，以代码为准，当场修正文档。
        - **过时即删**：过时的文档比没有文档更糟——宁可删，不要留错的。

        ## 何谓「大改动」（需要同步文档）

        满足任一条即属于必须更新文档的大改动：

        - 新增/删除/重命名 模块、命令、对外行为或目录结构 → `project.md`、`business.md`
        - 确立或修改 编码约定、禁用模式 → `conventions.md`
        - 引入新领域概念、改变核心流程或术语 → `business.md`
        - 踩坑、否决方案、识别敏感区 → `pitfalls.md`

        仅修 typo、调措辞、补单测断言等不改变行为的小改，可不动文档。

        ## 完成定义（收尾自检，大改动不得跳过）

        声称「已完成 / 可提交 / 可 merge」之前，逐条确认：

        1. 代码改动已通过可用检查（测试 / lint / 编译）。
        2. 若属于上文「大改动」，已更新对应 `.agentflow/` 文档。
        3. 文档与代码一致；每条信息只出现在一个文档里。
        4. 已按交接标准报告改动文件、命令、结果、风险。

        **未完成同步前，不要先宣布完成。**

        ## Skill 路由

        涉及专项操作时，先查 [`skills/README.md`](skills/README.md)
        的路由表，匹配则先读对应 skill 再动手。
        """
    )


def root_agents_pointer() -> str:
    return dedent(
        f"""\
        {AGENTFLOW_GENERATED_MARKER}
        # AGENTS.md

        本项目规范见 `.agentflow/AGENTS.md`，开工前先读。
        """
    )


def project_skeleton() -> str:
    return _skeleton(
        title="项目说明",
        writes="这个项目【是什么】：一句话定位、技术栈、整体架构、怎么启动运行",
        not_writes=(
            "怎么写代码（→ conventions.md）、业务规则与术语（→ business.md）、"
            "踩过的坑（→ pitfalls.md）、专项操作流程（→ skills/）"
        ),
        sections=[
            (
                "一句话定位",
                "用一句话说清这个项目是做什么的、解决什么问题。\n"
                "  例：一个离线 Python CLI，给多个 AI 编码工具搭统一的项目规范层。",
            ),
            (
                "技术栈",
                "列出语言、核心框架、关键依赖、运行环境。\n"
                "  基于真实的 pyproject.toml / package.json / Cargo.toml 等填写，不要猜。",
            ),
            (
                "架构概览",
                "描述主要模块、分层方式、数据流向。指向关键目录即可，\n"
                "  不要逐文件罗列。",
            ),
            (
                "启动与运行",
                "怎么安装依赖、怎么启动、怎么跑测试。给出真实命令。\n"
                "  只写「怎么跑」，不写「代码该怎么组织」（那属于 conventions.md）。",
            ),
        ],
    )


def conventions_skeleton() -> str:
    return _skeleton(
        title="编码规范",
        writes="这个项目【怎么写代码】：命名、结构、风格、禁用模式",
        not_writes=(
            "项目是什么/怎么运行（→ project.md）、业务规则（→ business.md）、"
            "历史踩坑（→ pitfalls.md）"
        ),
        sections=[
            (
                "命名约定",
                "文件、函数、变量、类的命名规则。只写本项目特有的约定，\n"
                "  语言通用惯例（如 Python 下划线）不必赘述。",
            ),
            (
                "代码结构",
                "模块如何组织、什么放哪里、新增功能该加在哪个目录。\n"
                "  只写结构规则，不重复 project.md 的架构概览。",
            ),
            (
                "风格与格式",
                "缩进、行长、import 顺序、注释密度等本项目坚持的风格。\n"
                "  有 lint/format 配置就直接指向它，别抄一遍。",
            ),
            (
                "禁用模式",
                "本项目明确【不】做的事。例：不引入新依赖、不写 God Object、\n"
                "  不在业务层用 print。给理由。",
            ),
        ],
    )


def business_skeleton() -> str:
    return _skeleton(
        title="业务说明",
        writes="这个项目的【业务】：领域概念、核心流程、术语表",
        not_writes=(
            "技术实现/架构（→ project.md）、代码风格（→ conventions.md）、"
            "技术踩坑（→ pitfalls.md）"
        ),
        sections=[
            (
                "核心概念",
                "这个领域里最关键的几个名词/实体，用一两句话解释。\n"
                "  例：订单、履约、结算。解释业务含义，不解释数据结构。",
            ),
            (
                "主要流程",
                "业务上「一件事从头到尾怎么走」。用步骤或流程描述，\n"
                "  不贴代码。",
            ),
            (
                "术语表",
                "项目里出现的、容易误解的业务术语。一词一行解释。\n"
                "  只收业务术语，不收通用技术词。",
            ),
        ],
    )


def pitfalls_skeleton() -> str:
    return _skeleton(
        title="历史踩坑与教训",
        writes="这个项目【踩过的坑】：历史教训、不再重蹈的决策、敏感区",
        not_writes=(
            "当前架构（→ project.md）、编码规范（→ conventions.md）、"
            "业务规则（→ business.md）。这里只记「过去犯过的错」。"
        ),
        sections=[
            (
                "踩过的坑",
                "记录过去遇到的问题和根因，以及如何避免再犯。\n"
                "  格式：现象 / 根因 / 对策。一条一个。",
            ),
            (
                "不再重蹈的决策",
                "曾经考虑过、最终否决的方案，以及否决理由。\n"
                "  防止后人（或 AI）再次踩进同一个坑。",
            ),
            (
                "敏感区",
                "改动风险高的地方、碰之前要三思的区域。\n"
                "  说明为什么敏感，不写怎么改（那是 conventions 的事）。",
            ),
        ],
    )


def skills_readme() -> str:
    return dedent(
        f"""\
        # Skill 路由

        {AGENTFLOW_GENERATED_MARKER}

        当任务匹配下表关键词时，**必须先读对应 skill 再动手**：

        | 任务关键词 | 先读 |
        |-----------|------|
        | <!-- 例：分页/列表/刷新 --> | <!-- skills/pagination.md --> |
        | <!-- 例：鉴权/登录/token --> | <!-- skills/auth.md --> |

        <!--
        维护规则（首个接手的 agent 填写）：
        - 扫描项目后，把本项目的真实 skill 触发条件填入上表。
        - 触发词写【祈使句/具体词】，不要写模糊描述。
          差：「处理分页」  好：「任务涉及 分页/列表刷新/页码 时」
        - 本项目暂无专项 skill 时，保留表头，表体留空即可。
        -->
        """
    )


def thin_entrypoint(platform: str, display: str | None = None) -> str:
    _ = display or PLATFORM_DISPLAY.get(platform, platform.title())
    return dedent(
        f"""\
        {AGENTFLOW_GENERATED_MARKER}
        本项目规范见 `.agentflow/AGENTS.md`，开工前先读。
        """
    )


def _skeleton(
    title: str,
    writes: str,
    not_writes: str,
    sections: list[tuple[str, str]],
) -> str:
    lines = [
        f"# {title}",
        "",
        "<!-- ═══════════════════════════════════════════════════════════",
        "     本文件边界（不可删除，不可改写）",
        f"     只写：{writes}",
        f"     不写：{not_writes}",
        "     判断标准：如果一段内容换到别的项目还能用，它就不属于这里。",
        "     ═══════════════════════════════════════════════════════════ -->",
        "",
        "<!-- 维护契约：由首个接触本项目的 AI 编码助手分析代码后填写；",
        "     后续每次接手时核对，与代码不符就修正。不要删除章节标题。 -->",
        "",
    ]
    for heading, hint in sections:
        lines.extend(
            [
                f"## {heading}",
                "",
                f"<!-- {hint} -->",
                "",
            ]
        )
    return "\n".join(lines)


AGENT_INSTRUCTIONS = dedent(
    """\
    你正在一个由 Flow 初始化规范地基的项目中工作。

    开工前必读：`.agentflow/AGENTS.md`（以及其索引的其它规范文档）。

    Flow 只负责文件结构与薄入口；文档填写与维护靠 AGENTS.md 中的契约：
    - 首次接手：先填未完成的骨架章节，再做用户任务。
    - 大改动（改了 命令/架构/对外行为/约定/业务/踩坑）：完成前必须同步对应 .agentflow 文档。
    - 完成定义：测试通过 + 文档已同步 + 每条信息只出现在一处；未同步前不要宣布完成。
    - 以代码为准：文档与代码冲突时改文档。
    """
)
