import { join } from "node:path";

/** Canonical spec skeleton paths (generated by init since v0.6.5). */
export const SPEC_DOC_FILES = [
  ".agentflow/docs/project.md",
  ".agentflow/docs/conventions.md",
  ".agentflow/docs/business.md",
  ".agentflow/docs/pitfalls.md",
] as const;

/** Pre-v0.6.5 flat layout — still accepted by check. */
export const LEGACY_SPEC_DOC_FILES: Record<
  (typeof SPEC_DOC_FILES)[number],
  string
> = {
  ".agentflow/docs/project.md": ".agentflow/project.md",
  ".agentflow/docs/conventions.md": ".agentflow/conventions.md",
  ".agentflow/docs/business.md": ".agentflow/business.md",
  ".agentflow/docs/pitfalls.md": ".agentflow/pitfalls.md",
};

export const BASE_REQUIRED_FILES = [
  ".agentflow/AGENTS.md",
  ".agentflow/prompts.md",
  ...SPEC_DOC_FILES,
  ".agentflow/skills/README.md",
] as const;

export function resolveRequiredPath(
  root: string,
  relative: string,
  exists: (path: string) => boolean,
): { path: string; relative: string; legacy: boolean } | null {
  const canonical = join(root, relative);
  if (exists(canonical)) {
    return { path: canonical, relative, legacy: false };
  }
  const legacyRelative =
    LEGACY_SPEC_DOC_FILES[relative as keyof typeof LEGACY_SPEC_DOC_FILES];
  if (legacyRelative) {
    const legacy = join(root, legacyRelative);
    if (exists(legacy)) {
      return { path: legacy, relative: legacyRelative, legacy: true };
    }
  }
  return null;
}
